### ISSUE TITLE
Use case for this plugin?

### ISSUE THREAD

**Issue by fregante** [anthonygreco/GSAPSnapPlugin#2]
GSAP supports SVGs through its CSSPlugin already: http://greensock.com/svg-transforms

You can just do:

```
TweenLite.to(snapElement.node, 1, {…})`
```

instead of 

```
TweenLite.to(snapElement, 1, {snap: {…}})`
```

**Comment by anthonygreco** [comment]
Sorry for the late reply. At the time it was handy for quickly moving from Raphael projects that were converted to Snap. Especially, since [DrawSVG](http://greensock.com/drawSVG) was released. 😄  Considering removing this repo entirely.

**Comment by bfred-it** [comment]
It's best to leave it with a note about its deprecation and the current alternative :)
